version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestJDBCSSLProject
  gitServerName: prabhakaribm
  gitUrl: https://github.com/prabhakaribm
  gitUsername: prabhakaribm
  gitBranch: main
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
